// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fukcxgvrpksgwyzpjiyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1a2N4Z3ZycGtzZ3d5enBqaXl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NzM4MjksImV4cCI6MjA1MDU0OTgyOX0.LCzVS6XDs2p1aq3spxfN1NpBtoLK8LxcIGp2PCfo4r0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);